version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily" # Check for updates daily
    open-pull-requests-limit: 10 # Limit the number of open PRs from Dependabot
    target-branch: "release/*" # Target all branches starting with "release/"
    allow:
      - dependency-type: "all"
        update-type: "version-update:semver-minor" # Only allow minor version updates
    commit-message:
      prefix: "fix(deps):"
      include: "scope"