name: Trigger Dependabot on vuln-fix tag

on:
  push:
    tags:
      - 'vuln-fix'

jobs:
  trigger-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get tagged branch
        id: get-branch
        run: |
          BRANCH=$(git branch -r --contains ${{ github.ref }} | grep -v HEAD | cut -d/ -f2-)
          echo "::set-output name=branch::$BRANCH"

      - name: Trigger Dependabot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/scans" \
            -d '{
              "dependency-type": "all",
              "directory": "/",
              "package-ecosystem": "maven",
              "ref": "refs/heads/${{ steps.get-branch.outputs.branch }}"
            }'